In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
from sklearn.model_selection import train_test_split
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing

ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/home/abhishek/.local/lib/python3.9/site-packages/traitlets/traitlets.py", line 632, in get
    value = obj._trait_values[self.name]
KeyError: '_control_lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abhishek/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
  File "/home/abhishek/.local/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 301, in dispatch_control
    async with self._control_lock:
  File "/home/abhishek/.local/lib/python3.9/site-packages/traitlets/traitlets.py", line 687, in __get__
    return t.cast(G, self.get(obj, cls))  # the G should encode the Optional
  File "/home/abhishek/.local/lib/python3.9/site-packages/traitlets/traitlets.py", line 649, in get
    value = self._validate(obj, default)
  File "/home/abhishek/.local/lib/python3.9/site-packages/traitlets/traitlets.py", line 722, in _validate
    value = self.validate(obj, value)
  File "/home/abhishek/.local/lib/python3.9/site-packages/traitlets/traitlets.py", line 2311, in validate
    self.error(obj, value)
  File "/home/abhishek/.local/lib/python3.9/site-packages/traitlets/traitlets.py", line 831, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The '_control_lock' trait of an IPythonKernel instance expected a Lock, not the NoneType None.

In [2]:

df = pd.read_csv("diabetes_prediction_dataset.csv")
display(df.head())

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

In [3]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['gender_encoded'] = le.fit_transform(df['gender'])
df  = df.drop(['gender'], axis=1)


df  = df.drop(['smoking_history'], axis=1)

In [4]:
display(df.head())

,age,hypertension,heart_disease,bmi,HbA1c_level,blood_glucose_level,diabetes,gender_encoded
0,80.0,0,1,25.19,6.6,140,0,0
1,54.0,0,0,27.32,6.6,80,0,0
2,28.0,0,0,27.32,5.7,158,0,1
3,36.0,0,0,23.45,5.0,155,0,0
4,76.0,1,1,20.14,4.8,155,0,1

In [5]:
from sklearn.tree import DecisionTreeClassifier
import numpy as np

X = df.drop(['diabetes'], axis=1)
y = df['diabetes']

X_train , X_test , y_train , y_test = train_test_split(X, y, test_size=0.2)

tree = DecisionTreeClassifier(random_state=0, max_depth=3).fit(X, y)


tree.fit(X_train , y_train)
tree.score(X_test , y_test)

0.97255

In [6]:
# # Get input from the user for each feature
# age = float(input("Enter Age: "))
# hypertension = float(input("Any hypertension? (0 for No, 1 for Yes): "))
# heart_disease = float(input("Any heart disease? (0 for No, 1 for Yes): "))
# bmi = float(input("Enter BMI: "))
# glucose = float(input("Enter Glucose "))
# gender = float(input("Enter gender: (0 for No, 1 for Yes)"))
# HbA1c_level = float(input("Enter HbA1c_level: "))


# # Create a DataFrame from the input values, ensuring column names match X_train
# new_data = pd.DataFrame([{
#       'age': age,
#       'hypertension': hypertension,
#       'heart_disease': heart_disease,
#       'bmi': bmi, 
#       'blood_glucose_level': glucose,
#       'gender_encoded': gender,
#       'HbA1c_level' : HbA1c_level
# }])

# # Ensure the columns of new_data match the order of X_train
# new_data = new_data[X_train.columns]


# # Make a prediction using the trained model
# prediction = tree.predict(new_data)


# # Interpret and display the prediction
# if prediction[0] == 1:
#    print("\nBased on the input, the person is predicted to have DIABETES.")
# else:
#    print("\nBased on the input, the person is predicted to NOT have DIABETES.")